language: ruby
rvm:
  - 2.3.3

# before_script:
#   - chmod +x ./script/cibuild # or do this locally and commit

install: gem install bundler html-proofer
script: bundle exec jekyll build --config _config.yml && htmlproofer ./_site

branches: 
  only:
    - master
    - dev 

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
