language: ruby
rvm:
- 2.4.1

addons:
  apt:
    packages:
      - sshpass

install: 
  - gem install bundler html-proofer
  - bundle install

script: bundle exec jekyll build --config _config.yml 
# && htmlproofer ./_site

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: dev

branches:
  only:
  - master
  - dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: olfH+ZJApupU0+wVei4Z9KEgQdf7IsKffPrmLtqSysrmfaSoclYuqlYVhvmyMy0MV/NUBKb5HSUp09Ip/vdO/Lllwzm8UpIVW1hNh1vr5lOHZ8RK/yZvrJMqaaeBQxRGbE2WItdWuDyjngzPJP1YZ1T9hFO/oGdPB2G2pg2kt8U/fhRl614fCDb71uugWNVKwpqOa8Ca7dgEzJrp+nOItBPeWNklp3r+3APQrUl9L+YX02JJHM4S3eD18JTk0kXBcFcV0tN5zgtvtsKojOWHlp5XbPlI92JgbRclnMwsGyZW5VVloNMFS9My3oz+y6KjmcwVamia0XEsvE9jH/QTLFzeUq/hRSaRxbcbIPZUSPT7Dz0OUhHu++Gos7HyQECxhL3SAWfyaLmdeOkSc+4i0tJFk+NsYUc4SF/v3EM6xueniv/XjALPwkTiRyRgV5J1ur5Y3nTicFu2qlt9vMAUXZEl5fyqnIUoawZ+Phj8+GaPd7fuX+MS1q8VPN5sXr7x2u3fZ7Ft1DjG5C0gqgrkSrS1Q2FrJIT125dDMANtEfsqTnOGFmH/o00yrlmF6jf7cIUMzIbAslH3iurKL8VvBw/6RG4J37Z9yV1/vGfvdvqnA3v67IUuoYyJfYjkODFtV1MOWRpu/BsP+XJ0zZ6QEjyWO88w6OolJxS4q/S08tI=

sudo: false
